# fly.toml app configuration file generated for space-grafana on 2024-07-03T11:21:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'space-grafana'
primary_region = 'cdg'

[build]

[mount]
  source = "grafana_storage"
  destination = "/var/lib/grafana"

[env]
  GF_INSTALL_PLUGINS = ""
  GF_AUTH_ANONYMOUS_ENABLED = "true"
  GF_SERVER_DOMAIN = "grafana.filstation.app"
  GF_SECURITY_ADMIN_PASSWORD__FILE="/var/lib/grafana/admin_password"

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1024mb'
